/**
 * Vendored-asset parity: verify the vendored anti-slop files against the
 * recorded manifest and (when present) the upstream clone.
 *
 * The manifest (scripts/vendored-manifest.json) is regenerated by
 * `scripts/sync-vendored.mjs`; this module is the testable core of the parity
 * check so vitest can exercise it without spawning a subprocess.
 *
 * @module dsh-anti-slop/src/parity
 */

import { createHash } from 'node:crypto'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { dirname, extname, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

/** Repo root (this module lives at src/parity.ts). */
export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')

/** Expected upstream revision. */
export const UPSTREAM_REVISION = '6d538555cb151d4121ed51a27db81890eacf8ae9'

/** Directory holding the vendored plugin sources. */
export const VENDORED_PLUGIN_DIR = join(REPO_ROOT, 'skills/install-anti-slop/assets/anti-slop')

/** The skill directory. */
export const SKILL_DIR = join(REPO_ROOT, 'skills/install-anti-slop')

/** Manifest path. */
export const MANIFEST_PATH = join(REPO_ROOT, 'scripts/vendored-manifest.json')

export function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex')
}

/** All .ts files under a directory, recursively, excluding *.test.ts. */
export function tsFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) return tsFiles(path)
    if (entry.name.endsWith('.test.ts')) return []
    return extname(entry.name) === '.ts' ? [path] : []
  })
}

/** The set of files this repo vendors (skill-root-relative, forward-slash). */
export function vendoredFiles(): string[] {
  const files = tsFiles(VENDORED_PLUGIN_DIR).map((path) => `assets/anti-slop/${relative(VENDORED_PLUGIN_DIR, path).split(sep).join('/')}`)
  files.push('SKILL.md')
  files.push('scripts/install.mjs')
  return files.sort()
}

export function fileHash(relativePath: string, base: string): string {
  return sha256(readFileSync(join(base, relativePath), 'utf8'))
}

export interface VendoredManifest {
  upstreamRevision: string
  upstreamUrl: string
  syncedFromClone: boolean
  files: Record<string, string>
}

export function readManifest(): VendoredManifest | null {
  if (!existsSync(MANIFEST_PATH)) return null
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as VendoredManifest
}

/** Result of a parity check. */
export interface ParityResult {
  ok: boolean
  failures: string[]
}

/**
 * Verify vendored files against the manifest and (when present) the upstream
 * clone's src. Returns a structured result rather than throwing, so tests can
 * assert on it.
 */
export function checkParity(): ParityResult {
  const failures: string[] = []
  const manifest = readManifest()
  if (manifest === null) {
    failures.push('no vendored-manifest.json; run `node scripts/sync-vendored.mjs` first')
    return { ok: false, failures }
  }
  if (manifest.upstreamRevision !== UPSTREAM_REVISION) {
    failures.push(`manifest upstreamRevision ${manifest.upstreamRevision} != expected ${UPSTREAM_REVISION}`)
  }
  const actual = vendoredFiles()
  const expected = Object.keys(manifest.files).sort()
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    failures.push('vendored file set differs from manifest; run sync')
  }
  for (const file of expected) {
    const hash = fileHash(file, SKILL_DIR)
    if (hash !== manifest.files[file]) {
      failures.push(`${file} hash differs from manifest`)
    }
  }
  // When the upstream clone exists, byte-compare against its src.
  const upstreamRoot = join(REPO_ROOT, 'anti-slop-upstream')
  const upstreamSrc = join(upstreamRoot, 'src')
  if (existsSync(upstreamSrc)) {
    for (const file of tsFiles(VENDORED_PLUGIN_DIR)) {
      const rel = relative(VENDORED_PLUGIN_DIR, file)
      const upstreamFile = join(upstreamSrc, rel)
      if (!existsSync(upstreamFile)) {
        failures.push(`vendored ${rel} has no upstream src counterpart`)
        continue
      }
      if (readFileSync(file, 'utf8') !== readFileSync(upstreamFile, 'utf8')) {
        failures.push(`vendored ${rel} differs from upstream src`)
      }
    }
    const ourSkill = join(SKILL_DIR, 'SKILL.md')
    const upSkill = join(upstreamRoot, 'skills/install-anti-slop/SKILL.md')
    const ourInstall = join(SKILL_DIR, 'scripts/install.mjs')
    const upInstall = join(upstreamRoot, 'skills/install-anti-slop/scripts/install.mjs')
    if (existsSync(upSkill) && !readFileSync(ourSkill, 'utf8').startsWith(readFileSync(upSkill, 'utf8'))) {
      failures.push('SKILL.md does not start with the upstream body (DSH appendix must follow)')
    }
    if (existsSync(upInstall) && readFileSync(ourInstall, 'utf8') !== readFileSync(upInstall, 'utf8')) {
      failures.push('install.mjs differs from upstream')
    }
  }
  return { ok: failures.length === 0, failures }
}
